PROC IMPORT OUT= WORK.MEthionine 
            DATAFILE= "C:\Users\nregmi3\OneDrive - University of Nebraska-Lincoln\3 - 825 and 930\0 - 930-Spring2023\Consultant Files\Neetu\Landon Tadich\GSL Methionine Full Sheet .xlsx"
            DBMS=EXCEL REPLACE;
     RANGE="Sheet1$"; 
     GETNAMES=YES;
     MIXED=NO;
     SCANTEXT=YES;
     USEDATE=YES;
     SCANTIME=YES;
RUN;
proc print data = methionine; run;
data methionine;
set methionine;
if past_16_17='Hay2' then past_16_17='Hay 2';
if birth_date>. and Calf_Wean_Wt>. then weaned=1;
else if birth_date>. and Calf_Wean_Wt=. then weaned=0;
if birth_date=. then weaned=.;
run;
proc sort data=methionine;
by Cow_ID year;
run;
proc freq data=methionine;
table year*Past_16_17;
run;
proc sort data=methionine;
by year;
run;
*determine first day of calving season each year in order to have covariate of dayseason;
data meth2;
set methionine;
if birth_date=. then delete;
run;
proc sort data=meth2;
by year birth_date;
run;
data first;
keep year first_date;
format first_date date9.;
set meth2;
by year birth_date;
first_date=birth_date;
if first.year then output;
run;
*this is the cow data;
data methcow;
merge methionine first;
by year;
dayseason=birth_date-first_date+1;
run;
*this is the calf data;
data meth3;
merge methionine first;
by year;
dayseason=birth_date-first_date+1;
if sex in ('H','B');
chgdeccalv=PreCalf_BCS-Dec_BCS;
chgdecpbrd=PreBreed_BCS-Dec_BCS;
chgdecwn=BCS-Dec_BCS;
if Calf_Wean_Wt > . then calfwn=1;
else calfwn=0;
*recoded this calf to the appropriate gender, since it has carcass data;
if calf_id=8103 then sex='B';
run;
proc sort data=meth3;
by sex;
proc freq data = meth3;
table calfwn*trt;
run;
proc means data=meth3;
by sex;
var Calf_Wean_Wt;
run;
options nodate nonumber;
*ods html body='your_file.html';
ods printer pdf file='C:\Users\Kathy\Statistics clients\Landon Tadich (Rick F SC3L)\Calf Birth and Pre-breeding Wt 03282023.pdf';
run;
title1 'Initial Analysis of Calf Birth Weight with fixed effects';
title2 'year, treatment, calf gender, and linear day in calving season';
title3 ' and random year*treatment and repeated measures to account for';
title4 'cows having multiple records';
run;
proc glimmix data=meth3;
if calf_id=8103 then sex='B';
class year cow_id past_16_17 trt sex;
model birth_wt= year trt sex dayseason;
random intercept /subject=year*trt;
random _residual_/subject=cow_id(trt) type=cs;
lsmeans trt sex year/diff adj=tukey;
run;
title1 'Initial Analysis of Calf Weight prior to breeding season with fixed effects';
title2 'year, treatment, calf gender, and linear day in calving season';
title3 ' and random year*treatment and repeated measures to account for';
title4 'cows having multiple records';
run;
ods rtf;
proc glimmix data=meth3;
if calf_id=8103 then sex='B';
class year cow_id past_16_17 trt sex;
model PreBreed_Calf_Wt= year trt sex dayseason/s;
random intercept/subject=year*trt;
random _residual_/subject=cow_id(trt) type=cs;
lsmeans trt sex year/diff adj=tukey plot=meanplot(join cl);
run;
ods printer close;
ods rtf close;
options nodate number;
*ods html body='your_file.html';
ods printer pdf file='C:\Users\Kathy\Statistics clients\Landon Tadich (Rick F SC3L)\Pregnancy Rate 04122023.pdf';
run;
title1 'Initial Analysis of pregnancy rate with fixed effects';
title2 'year, treatment, calf gender, and linear day in calving season';
title3 ' and random year*treatment. Because cows who are not pregnant are dropped';
title4 'repeated measures term is not included. Binomial Distribution';
run;

ods rtf;
proc glimmix data=meth3;
class year cow_id past_16_17 trt sex;
model preg=  trt  dayseason/dist=bin s oddsratio (diff=all) ;
random intercept/subject=year*trt;
*random _residual_/subject=cow_id(trt) type=cs;
lsmeans trt /diff adj=tukey ilink cl odds plot =  meanplot (join cl;
run;
title1 'Final Analysis of pregnancy rate with fixed effects';
title2 'treatment and linear day in calving season (drop non significant terms)';
title3 ' and random year*treatment. Because cows who are not pregnant are dropped';
title4 'repeated measures term is not included. Binomial Distribution';
run;
ods rtf close;
proc glimmix data=meth3;
class year cow_id past_16_17 trt sex;
model preg= trt dayseason/dist=bin s oddsratio (diff=all) ;
random intercept/subject=year*trt;
*random _residual_/subject=cow_id(trt) type=cs;
lsmeans trt /diff adj=tukey ilink cl odds;
run;
ods printer close;
run;
*cow body condition score. The december BCS can be used as a baseline value;
 
title1 'Initial Analysis of Cow BCS prior to start of treatment with fixed effects';
title2 'year, treatment';
title3 ' and random year*treatment and repeated measures to account for';
title4 'cows having multiple records';
run;
proc glimmix data=meth3;
class year cow_id past_16_17 trt sex;
model Dec_BCS= year trt/s;
random intercept/subject=year*trt;
random _residual_/subject=cow_id(trt) type=cs;
lsmeans trt year/diff adj=tukey;
run;
title1 'Initial Analysis of Cow BCS prior to start of treatment with fixed effects';
title2 'year, treatment';
title3 ' and random year*treatment and repeated measures to account for';
title4 'cows having multiple records';
run;
proc glimmix data=meth3;
class year cow_id past_16_17 trt sex;
model PreCalf_BCS= year trt Dec_BCS/s;
random intercept/subject=year*trt;
random _residual_/subject=cow_id(trt) type=cs;
lsmeans trt year/diff adj=tukey;
run;
title1 'Analysis of change in Cow BCS from prior to start of treatment (Dec) to';
title2 'Precalving with fixed effects year, treatment and sex';
title3 ' and random year*treatment and repeated measures to account for';
title4 'cows having multiple records';
run;
ods rtf;
proc glimmix data=meth3;
class year cow_id past_16_17 trt sex;
model chgdeccalv= year trt dayseason/s;
random intercept/subject=year*trt;
random _residual_/subject=cow_id(trt) type=cs;
lsmeans trt year/diff adj=tukey plot = meanplot(join cl);
run;
ods rtf close;
title1 'Analysis of change in Cow BCS from prior to start of treatment (Dec) to';
title2 'Precalf with fixed effects year, treatment and day incalving season calved';
title3 ' and random year*treatment and repeated measures to account for';
title4 'cows having multiple records';
run;
proc glimmix data=meth3;
class year cow_id past_16_17 trt sex;
model chgdecpbrd= year trt dayseason/s;
random intercept/subject=year*trt;
random _residual_/subject=cow_id(trt) type=cs;
lsmeans trt year/diff adj=tukey;
run;
title1 'Analysis of change in cow BCS from prior to start of treatment (Dec) to';
title2 'Prebreed with fixed effects year, treatment and day incalving season calved';
title3 'and random year*treatment and repeated measures to account for';
title4 'cows having multiple record';
run;
proc glimmix data=meth3;
class year cow_id past_16_17 trt sex;
model chgdecwn= year trt dayseason/s;
random intercept/subject=year*trt;
random _residual_/subject=cow_id(trt) type=cs;
lsmeans trt year/diff adj=tukey;
run;
title1 'Analysis of change in Cow BCS from prior to start of treatment (Dec) to';
title2 'overall BSC of cow with fixed effects year, treatment and day incalving season calved';
title3 'and random year*treatment and repeated measures to account for';
title4 'cows having multiple records';
run;
ods rtf close;
proc freq data=meth3;
table grade*trt;
run;
data want;
   set meth3;
   new_hcwt = input(HCWT, 8.);
   drop HCWT;
run;
proc print data = want; run;
ods rtf;
proc glimmix data= want;
class year cow_id past_16_17 trt sex;
model new_HCWT = year trt/s;
random intercept/subject = year*trt;
random _residual_/subject = cow_id(trt) type = cs;
lsmeans trt year /diff  adj=tukey;
run;
title1 'Analysis of HCWT with fixed effects year, trt and random year*trt';
title2 'and repeated measures to account for cows having multiple records';
run;
data want1;
set meth3;
new_yg = input(YG, 8.);
drop yg;
run;
*proc print data = want1; *run;
proc glimmix data = want1;
class year cow_id past_16_17 trt;
model new_YG = year trt/s;
random intercept/subject = year*trt;
random _residual_/subject = cow_id(trt) type = cs;
lsmeans trt year/diff adj = tukey;
run;
title1 'Analysis of YG with fixed effects year,trt and random year*trt';
title2 'and repeated measures to account for cows having multiple records';
run;
data newdat;
set want1;
if Q_Grade = 'CHO'  then Grd =1;
else if Q_Grade = 'PRM' or Q_Grade = 'Sel' then Grd =0;
run;
proc glimmix data = newdat;
class year cow_id past_16_17 trt;
model grd = year trt/s dist= bin oddsratio (diff = all);
random intercept/subject=year*trt;
*random _residual_/subject=cow_id(trt) type=cs;
lsmeans trt /diff adj=tukey ilink cl odds;
run;
title1 'Analysis of Quality grade with fixed effects year, trt and random year*trt';
run;
data want2;
set newdat;
new_rea = input(rea, 8.);
drop rea;
run;
proc glimmix data = want2;
class year cow_id past_16_17 trt;
model new_rea = year trt/s;
random intercept/subject = year*trt;
random _residual_/subject = cow_id(trt) type = cs;
lsmeans year trt/diff adj = tukey;
run;
title1 'Analysis of Ribeye with fixed effects year, trt';
title2 'and repeated measures to account for cows having multiple records';
run;
data want2;
set newdat;
new_marb = input(marb, 8.);
drop marb;
run;
proc glimmix data = want2;
class year cow_id past_16_17 trt;
model new_marb = year trt /s;
random intercept/subject = year*trt;
random _residual_/subject = cow_id(trt) type = cs;
lsmeans year trt/diff adj = tukey;
run;
title1 'Analysis of marbling with fixed effects year, trt';
title2 'and repeated measures to account for cows having multiple records';
run;
data want2;
set newdat;
new_backfat = input(backfat, 8.);
drop backfat;
run;
proc glimmix data = want2;
class year cow_id past_16_17 trt;
model new_backfat = year trt /s;
random intercept/subject = year*trt;
random _residual_/subject = cow_id(trt) type = cs;
lsmeans year trt/diff adj = tukey;
run;
title1 'Analysis of backfat with fixed effects year, trt';
title2 'and repeated measures to account for cows having multiple records';
run;
ods rtf close;

ods rtf;
proc freq  data = newdat;
table Q_grade*trt;
run;
ods rtf close;

*calf weaning weight;
proc glimmix data = meth3 plot=residualpanel;
class year cow_id trt sex;
model Calf_Wean_Wt = year trt sex dayseason;
random intercept/subject = year*trt;
random _residual_/subject = cow_id(trt) type = cs;
lsmeans trt sex year/ diff adj = tukey plot = meanplot(join cl);
run;

*Weaning weight;
proc glimmix data = meth3 plot = residualpanel ;
class year cow_id past_16_17 trt sex;
*ch = Wt___Wean - Dec_Wt;
model Wt___Wean = year trt sex dayseason; *precalf_wt as covariate, dayseason and sex were not significant;
random intercept/subject = year*trt;
random _residual_/subject= cow_id(trt) type = cs;
lsmeans trt year sex /diff adj = tukey;
run;
